### ISSUE TITLE
images for documentation

### ISSUE THREAD

**Issue by buehler** [smartive/proc-that#3]

**Comment by petermanser** [comment]
Here we go.
![emblemmatic-proc-that-logo-417](https://cloud.githubusercontent.com/assets/292951/14951741/8a7007c8-105b-11e6-8043-b3d1652d2f66.png)

**Comment by petermanser** [comment]
![proc-that-logo](https://cloud.githubusercontent.com/assets/292951/14951779/d2fc0f96-105b-11e6-80b5-5a15747b90bf.png)
